name = "weekly-lunch-orders"

account_id = "bbf7369bf71453ff85da6e28335e8a06"

main = "src/worker.ts"
compatibility_date = "2025-06-30"

[[d1_databases]]


binding = "DB"
database_name = "lunch_orders"
database_id = "67d6a539-a52f-47d1-b353-75160c767d3a"



[assets]
directory = "./dist"
binding = "ASSETS"
